# This is a weird way of telling Travis to use the fast container-based test
# runner instead of the slow VM-based runner.
sudo: false

language: go

go:
  - 1.14.x

before_script:
  - GOFLAGS='' go get -u golang.org/x/lint/golint
  - GOFLAGS='' go get golang.org/x/tools/cmd/cover
  - GOFLAGS='' go get github.com/mattn/goveralls

script:
  - make lint
  - make test
  - make race
  - make coverage

after_success:
  - $GOPATH/bin/goveralls -service=travis-ci
